"""Draw the BridgeToLeads icon (needs Pillow). Regenerates bridgetoleads.ico/.png and brand_icon.py.

    python3 tools/prospection/assets/make_icon.py
"""
import base64
import io
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
S = 1024  # drawn large, then downsampled for smooth edges
STOPS = [(0.0, (124, 58, 237)), (0.55, (236, 72, 153)), (1.0, (249, 115, 22))]  # violet → rose → orange


def lerp_stops(t):
    for (t0, c0), (t1, c1) in zip(STOPS, STOPS[1:]):
        if t <= t1:
            k = (t - t0) / (t1 - t0)
            return tuple(round(a + (b - a) * k) for a, b in zip(c0, c1))
    return STOPS[-1][1]


def draw():
    grad = Image.new("RGB", (S, S))
    px = grad.load()
    for y in range(S):
        for x in range(S):
            px[x, y] = lerp_stops((x + y) / (2 * S - 2))
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, S - 1, S - 1), radius=230, fill=255)
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    img.paste(grad, (0, 0), mask)

    d = ImageDraw.Draw(img)
    white, yellow = "white", (254, 240, 138)
    deck_y, left, right = 650, 150, 874
    # Arch of the bridge (drawn as a thick arc of a large ellipse).
    d.arc((230, 330, 794, 970), start=180, end=360, fill=white, width=62)
    # Hangers between the arch and the deck.
    for x in (330, 420, 512, 604, 694):
        top = 650 - int((1 - ((x - 512) / 282) ** 2) ** 0.5 * 320) + 30
        d.line((x, top, x, deck_y), fill=white, width=26)
    # Deck, with rounded ends.
    d.line((left, deck_y, right, deck_y), fill=white, width=64)
    for x in (left, right):
        d.ellipse((x - 32, deck_y - 32, x + 32, deck_y + 32), fill=white)
    # Pillars under the deck.
    for x in (262, 762):
        d.rounded_rectangle((x - 30, deck_y, x + 30, 850), radius=14, fill=white)
    # The lead waiting on the other side.
    d.ellipse((right - 70, deck_y - 190, right + 20, deck_y - 100), fill=yellow)
    return img


def main():
    img = draw()
    img.save(HERE / "bridgetoleads.ico", sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    img.resize((256, 256), Image.LANCZOS).save(HERE / "bridgetoleads.png")
    buf = io.BytesIO()
    img.resize((64, 64), Image.LANCZOS).save(buf, "PNG", optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode()
    lines = [b64[i:i + 76] for i in range(0, len(b64), 76)]
    (HERE.parent / "brand_icon.py").write_text(
        '"""Generated by assets/make_icon.py: 64px window icon, base64 PNG."""\n\nICON_PNG_B64 = (\n'
        + "".join(f'    "{line}"\n' for line in lines) + ")\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
