"""Draw the Lead Finder icon (needs Pillow). Regenerates lead_finder.ico and brand_icon.py.

    python3 tools/prospection/assets/make_icon.py
"""
import base64
import io
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).resolve().parent
S = 1024  # drawn large, then downsampled for smooth edges
STOPS = [(0.0, (124, 58, 237)), (0.55, (236, 72, 153)), (1.0, (249, 115, 22))]  # violet → rose → orange


def lerp_stops(t):
    for (t0, c0), (t1, c1) in zip(STOPS, STOPS[1:]):
        if t <= t1:
            k = (t - t0) / (t1 - t0)
            return tuple(round(a + (b - a) * k) for a, b in zip(c0, c1))
    return STOPS[-1][1]


def draw():
    grad = Image.new("RGB", (S, S))
    px = grad.load()
    for y in range(S):
        for x in range(S):
            px[x, y] = lerp_stops((x + y) / (2 * S - 2))
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle((0, 0, S - 1, S - 1), radius=230, fill=255)
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    img.paste(grad, (0, 0), mask)

    d = ImageDraw.Draw(img)
    cx, cy, r, w = 430, 430, 230, 78
    d.line((cx + 150, cy + 150, 800, 800), fill="white", width=120)            # handle
    d.ellipse((800 - 60, 800 - 60, 800 + 60, 800 + 60), fill="white")         # rounded handle end
    d.ellipse((cx - r, cy - r, cx + r, cy + r), outline="white", width=w)      # lens ring
    d.ellipse((cx - 70, cy - 70, cx + 70, cy + 70), fill=(254, 240, 138))     # yellow "found it" dot
    return img


def main():
    img = draw()
    img.save(HERE / "lead_finder.ico", sizes=[(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)])
    img.resize((256, 256), Image.LANCZOS).save(HERE / "lead_finder.png")
    buf = io.BytesIO()
    img.resize((64, 64), Image.LANCZOS).save(buf, "PNG", optimize=True)
    b64 = base64.b64encode(buf.getvalue()).decode()
    lines = [b64[i:i + 76] for i in range(0, len(b64), 76)]
    (HERE.parent / "brand_icon.py").write_text(
        '"""Generated by assets/make_icon.py: 64px window icon, base64 PNG."""\n\nICON_PNG_B64 = (\n'
        + "".join(f'    "{line}"\n' for line in lines) + ")\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
